### ISSUE TITLE
Multiple page toc("*.md") aborts due to warnings

### ISSUE THREAD

**Issue by mtpultz** [assemble/verb#18]
Separating sections of the projects readme into subsequent markdown files and using {%= toc("docs//*.md") %}, or a more complex version {%= toc(["docs//*.md", "!docs//*.tmpl.md"]) %}, produces a warning of "Cannot call method 'indexOf' of undefined Use" before aborting.

**grunt verb --v** produces:

> Running "verb:readme" (verb) task
Verifying property verb.readme exists in config...OK
Files: [no src] -> README.md
Files: docs/README.tmpl.md -> README.md
Options: sep="\n", ext=".md", data=["docs/*.{json,yml}"], prefixBase, cwd="d:\\htdocs\\test", destBase="d:\\htdocs\\test", docs="docs"
Writing d:/htdocs/ubc/README.md...OK
File "README.md" created.
Reading docs/README.tmpl.md...OK
Warning: Cannot call method 'indexOf' of undefined Use --force to continue.
Aborted due to warnings.

from a **README.tmpl.md** source containing either one of the following:
* {%= toc("*.md") %}
* {%= toc("docs//*.md") %}
* {%= toc(['docs//*.md', '!*docs//*.tmpl.md']) %}

**Comment by jonschlinkert** [comment]
fixed a while back, but improved in 0.7.0. See [the table of contents recipe)[https://github.com/assemble/verb/blob/master/recipes/generate-a-table-of-contents.md]
