### ISSUE TITLE
Partial inside a partial

### ISSUE THREAD

**Issue by dac09** [assemble/verb#23]
Hi,

I'm trying to nest partials, but that doesn't seem to work.

Basically:
base = partial1 + partial2 + partial3

where,
partial1 = subpartial1 + subPartial2

Is this possible using the {%= docs(partial) %} syntax? Ideally we could just tell it specially where the file is, rather than always have it reference docs/

Any help would be greatly appreciated.

Thanks

**Comment by jonschlinkert** [comment]
this should be possible now. please reopen or create a new issue if you have any more issues with this
