### ISSUE TITLE
Deprecation warning: moment.lang is deprecated. Use moment.locale instead

### ISSUE THREAD

**Issue by robmcguinness** [assemble/verb#24]
Minor warning issued when running **gulp-verb**.  Basically `momment.lang` was renamed to `moment.locale`

```markdown
Copyright (c) {%= date('YYYY') %} {%= author.name %}
```
https://github.com/assemble/verb/blob/40f3eb0056eed4708b8cba78e1b7c7de63ad55d2/lib/tags/date.js#L22

**Comment by jonschlinkert** [comment]
fixed in the date helper
