### ISSUE TITLE
Can't find task default

### ISSUE THREAD

**Issue by Melindrea** [assemble/verb#32]
I am using verb for a project (no grunt or gulp, etc). After installing it both in that project and globally, i run `verb` in the CLI, with the following errors:

```
[07:48:55]$ verb

[07:48:58] using verbfile /home/marie/.nvm/v0.10.17/lib/node_modules/verb/lib/_verbfile.js
[07:48:59] task 'default' is not in your verbfile
[07:48:59] please check the documentation for proper verbfile formatting
```

I have the doc files stored under `docs/*.md`, and my `.verb.md` is as follows:

```
# {%= name %}

> {%= description %}

## Dependencies
{%= include("docs/dependencies") %}

## Server
{%= include("docs/server") %}

## Route
{%= include("docs/route") %}

## Author
{%= include("author") %}

## License
{%= copyright() %}
{%= license() %}

***

{%= include("footer") %}
``` 

That is, my `.verb.md` is very close to the default  example.

**Comment by jonschlinkert** [comment]
should have been resolved a while ago. let me know if you still have the issue

**Comment by Melindrea** [comment]
Since I finally actually tested verb again ... Nope, no longer having this issue.
