### ISSUE TITLE
changelog.js example in Verb 0.2.5 uses json but plasma call was expecting yaml

### ISSUE THREAD

**Issue by jwtd** [assemble/verb#33]
It seems that the current grunt-verb module is pulling in Verb v0.2.5. In its samples directory I found an include and data file for changelogs. I tried adding it to my README.src.md, but when I did I got the error:
```
Warning: Object #<Object> has no method 'indexOf' Use --force to continue.
```

I was able to get it working by updating:
https://github.com/assemble/verb/blob/v0.2.5/lib/tags/changelog.js#L24
```
    //data = plasma({src: dataFile}, {lang: 'yaml'});
    data = plasma([dataFile]);
```
The sample uses a json file for data, but the tags code had a plasma call that was expecting yaml.

**Comment by jwtd** [comment]
Actually, that didn't help, because the datafile in the sample isn't structured correctly either. Disregard this issue.

**Comment by jonschlinkert** [comment]
This is all fixed with the next version of verb. Sorry I've been traveling but this is at the top of my list to fix.
