### ISSUE TITLE
TypeError: Object #<Helpers> has no method 'resolve'

### ISSUE THREAD

**Issue by mightyiam** [assemble/verb#38]
![screenshot from 2015-02-19 18 03 12](https://cloud.githubusercontent.com/assets/635591/6270354/f44e6746-b861-11e4-8df3-192c438eaf36.png)

**Comment by mightyiam** [comment]
Otherwise, I would really like to use it!

**Comment by doowb** [comment]
@mightyiam try getting verb again by doing the following:

> for global

```bash
$ npm uninstall -g verb
$ npm clear cache -g
$ npm i -g verb
```

> for local

```bash
$ npm uninstall verb
$ npm clear cache
$ npm i verb
```

**Comment by jonschlinkert** [comment]
yeah, this should work. we got this fixed earlier. let us know if you have any more issues

**Comment by mightyiam** [comment]
Thank you!
