### ISSUE TITLE
include("author") invents twitter link

### ISSUE THREAD

**Issue by mightyiam** [assemble/verb#39]
I didn't specify my twitter username anywhere. Seems like just a wrong guess.

And there's this object string, as well.
```md
**[object Object]**
 
+ [github/mightyiam](https://github.com/mightyiam)
+ [twitter/mightyiam](http://twitter.com/mightyiam) 
```

**Comment by jonschlinkert** [comment]
Yeah, I know exactly what that is, I can fix it. It's great getting these issues b/c most of the defaults in verb are based on how I configure things for my projects (that's my frame of reference, right :) 

I'll get this fixed, in the meantime, if you ever need to override something in a project - like to add or override data to pass to templates, you can also add front-matter to any template, like `.verb.md` and it should work.

e.g.

```yaml
---
username: foo
---
{%= username %}
```

**Comment by jonschlinkert** [comment]
The `{%= include("author") %}` template is used in the default `.verb.md`, which includes both a twitter link and a github link. It's not necessary to keep this default template though. 

You can create your own custom template using whatever data you want. For example, this would insert the author's name from package.json (bolded):

```js
**{%= author.name %}**
```

In the 0.7.0 release you can also easily load your own custom templates or template modules by setting values in the command line. [Read more about it here](https://github.com/assemble/verb/issues/44)

**Comment by jonschlinkert** [comment]
closing since this should be resolved
