### ISSUE TITLE
{%= license() %} gives error

### ISSUE THREAD

**Issue by mightyiam** [assemble/verb#40]

**Comment by mightyiam** [comment]
Yup. Gives error. Am I supposed to have
```json
{
  "license": {
    "type": "foo",
    "url": "http://example.com"
  }
}
```
Or
```json
{
  "license": "foo"
}
```
?

**Comment by jonschlinkert** [comment]
You should be able to use whatever format you want. however, I think the recommended format would be an object if you use one license, or an array if you use multiple, (like MIT and CC etc).

**Comment by mightyiam** [comment]
Seems to be [an official stand](https://docs.npmjs.com/files/package.json#license).

**Comment by jonschlinkert** [comment]
yeah, I use those. thanks

**Comment by jonschlinkert** [comment]
please try with verb-cli 0.6.0 and verb 0.7.0. if it works for you please close, or let me know if you're still having issues. should be easier to fix now

**Comment by jonschlinkert** [comment]
going to go ahead and close this @mightyiam. please reopen or create a new issue if necessary

**Comment by mightyiam** [comment]
Thank you @jonschlinkert!

**Comment by jonschlinkert** [comment]
:+1:
