### ISSUE TITLE
Getting apidocs to work

### ISSUE THREAD

**Issue by stefanwalther** [assemble/verb#43]
Hi,

I am fortunately and finally making progress getting verb to work on my system, really sweet. As soon as I fully get the picture I'll post a how-to/get-started since I assume that there might be other people thinking of a good workflow how to use that in several projects.

But as of now I have a specific question:

`{%= apidocs("./lib/extinfo/index.js") %}` and `{%= related([]) %}` from `.verb.md` don't get resolved, what could be the reason for that?

Regards
Stefan

**Comment by stefanwalther** [comment]
Solved it, forgot to add `@api public` ... now it works ...

**Comment by jonschlinkert** [comment]
> Solved it, forgot to add

great! glad you got it working. And btw, I finished re-writing the API docs helper today. it uses about 1/5 of the code and is a little faster. but more importantly it should be easier to use it as an example to create a custom helper if necessary. 

I'm also almost finished with the refactor of verb itself. getting the deps updated and tests are the time consuming part...

**Comment by stefanwalther** [comment]
+1 !!!
