### ISSUE TITLE
`copyright()` should use `package.json`'s copyright prop

### ISSUE THREAD

**Issue by mightyiam** [assemble/verb#45]
Where does this issue belong?

**Comment by mightyiam** [comment]
If there is no `package.json` copyright prop then it may use the `package.json` `author` field (as it seems to do now by default).

**Comment by jonschlinkert** [comment]
let me know if that works for you

**Comment by mightyiam** [comment]
I would if it weren't for https://github.com/assemble/verb/issues/46.

**Comment by mightyiam** [comment]
Seems to work. Thank you very much!
