### ISSUE TITLE
missing `template-helper-apidocs` version

### ISSUE THREAD

**Issue by mightyiam** [assemble/verb#46]
![screenshot_2015-04-26_14-45-37](https://cloud.githubusercontent.com/assets/635591/7337062/1837de68-ec23-11e4-8778-8ae00c62713e.png)

**Comment by jonschlinkert** [comment]
should be fixed. I knew this was happening but was kicked offline before I could fix it yesterday and couldn't get back on. no idea why my internet was down. sorry about the issue
